import type { Nuxt } from 'nuxt/schema'
import { existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

// ============================================================================
// Public API — module configuration for nuxt.config.ts
// ============================================================================

export interface ModuleOptions {
  /**
   * Optimize CSS output.
   * - `true` | `'inline'`: Tree-shake CSS per-page and inline into `<style>`
   * - `'file'`: Tree-shake globally and output single `/css/optimized.css`
   * - `false`: Skip CSS optimization
   * @default false
   */
  optimizeCss?: boolean | 'inline' | 'file'

  /** @deprecated Use `optimizeCss` instead */
  inlineStyles?: boolean

  /**
   * Strip HTML attributes generated by Vue SSR.
   * Useful for reducing output size and removing framework markers.
   * @default ['data-v-', '__vue_ssr__', 'data-server-rendered']
   */
  stripAttributes?: string[]
}

// ============================================================================
// Internal types
// ============================================================================

export type CssMode = 'inline' | 'file' | 'none'

export interface ExtendedOptions extends ModuleOptions {
  _cssMode: CssMode
}

export interface ProcessResult {
  cleaned: number
  payloads: number
  cssOptimized: number
}

export interface FileResult {
  cleaned: boolean
  payload: boolean
  cssOptimized: boolean
}

// ============================================================================
// Constants — essential selectors that must always be preserved
// ============================================================================

export const ESSENTIAL_SELECTORS = Object.freeze([
  'html', 'body', 'head', ':root', '.dark',
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  'p', 'a', 'span', 'div', 'img', 'svg',
  'ul', 'ol', 'li', 'table', 'tr', 'td', 'th',
  'blockquote', 'pre', 'code', 'hr',
  '*::before', '*::after', '*::-webkit-scrollbar',
  '::selection', '::placeholder',
  // Nuxt page transitions — required for SPA navigation
  'page-enter-active', 'page-enter-from', 'page-enter-to',
  'page-leave-active', 'page-leave-from', 'page-leave-to',
]) as ReadonlyArray<string>

// File patterns to exclude from CSS collection
export const SKIP_CSS_FILES = Object.freeze(['optimized.css', 'main.css'])

// ============================================================================
// Regex patterns — HTML extraction
// ============================================================================

export const CLASS_RE = /\bclass=["']([^"']*)["']/g
export const ID_RE = /\bid=["']([^"']*)["']/g
export const DATA_RE = /\bdata-([a-zA-Z0-9_-]+)=/g
export const HTML_TAG_RE = /<([a-z][a-z0-9]*)\b[^>]*>/gi

// ============================================================================
// Regex patterns — HTML cleaning
// ============================================================================

export const CSS_LINK_RE = /<link[^>]*rel="stylesheet"[^>]*href="[^"]*"[^>]*\/?>\s*/g
export const STYLE_TAG_RE = /<style[^>]*>[\s\S]*?<\/style>\s*/g
export const VUE_RUNTIME_RE = /<script[^>]*type="module"[^>]*src="\/_nuxt\/[^"]*"[^>]*><\/script>/g
export const MODULEPRELOAD_RE = /<link[^>]*rel="modulepreload"[^>]*href="\/_nuxt\/[^"]*"[^>]*>/g
export const PREFETCH_RE = /<link[^>]*rel="(preload|prefetch)"[^>]*href="\/_nuxt\/[^"]*\.js[^"]*"[^>]*>/g
export const NUXT_DATA_RE = /<script[^>]*id="__NUXT_DATA__"[^>]*>([\s\S]*?)<\/script>/

// ============================================================================
// Regex patterns — CSS parsing
// ============================================================================

export const CSS_COMMENT_RE = /\/\*[\s\S]*?\*\//g
export const CSS_WS_RE = /\s+/g
export const SKIP_AT_RULE_RE = /^@(?:charset|import)\b/
export const PRESERVE_AT_RULE_RE = /^@(?:font-face|keyframes|-webkit-keyframes)\b/

// ============================================================================
// Pure helpers (no side effects)
// ============================================================================

export function resolveCssMode(options: ModuleOptions): CssMode {
  if (options.optimizeCss === 'file') return 'file'
  if (options.optimizeCss === 'inline') return 'inline'
  if (options.optimizeCss === true) return 'inline'
  if (options.inlineStyles) return 'inline'
  return 'none'
}

export function findOutputDir(nuxt: Nuxt): string | null {
  const candidates = [
    nuxt.options.rootDir && join(nuxt.options.rootDir, 'dist'),
    nuxt.options.nitro.output?.dir,
    '.output/public',
  ]
  for (const d of candidates) {
    if (d && existsSync(d) && readdirSync(d).length > 0) return d
  }
  return null
}
